server/first/urls.py
from django.contrib import admin
from django.conf.urls import handler404
from django.urls import path, re_path, include

handler404 = 'www.views.handler404'

# path(r'admin/', admin.site.urls),
urlpatterns = [
    path(r'api/', include('rest.urls')),
    path(r'', include('www.urls')),
]

server/www/urls.py
from django.urls import path, re_path, include

from . import views

app_name = 'www'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'profile', views.profile, name='profile'),

    path(r'login', views.login, name='login'),
    re_path(r'^login/(?P<service>[a-z]+)$', views.login, name='login'),
    re_path(r'^oauth/(?P<service>[a-z]+)$', views.oauth, name='oauth'),
    path(r'logout', views.logout, name='logout'),

    path(r'register', views.register, name='register')
]

server/www/models.py
#-------------------------------------------------------------------------------
#
#   FIRST Django ORM Models
#   Copyright (C) 2017  Angel M. Villegas
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#-------------------------------------------------------------------------------


#   Python Modules
from __future__ import unicode_literals

#   Third Party Modules
from django.db import models
from django.utils import timezone


class User(models.Model):
    id = models.BigAutoField(primary_key=True)

    name = models.CharField(max_length=128)
    email = models.CharField(max_length=254)
    handle = models.CharField(max_length=32)
    number = models.IntegerField()
    api_key = models.UUIDField(unique=True)
    created = models.DateTimeField(default=timezone.now)
    rank = models.BigIntegerField(default=0)
    active = models.BooleanField(default=True)

    service = models.CharField(max_length=16)
    auth_data = models.CharField(max_length=32768)

    @property
    def user_handle(self):
        return '{0.handle}#{0.number:04d}'.format(self)

    def dump(self, full=False):
        data = {'handle' : self.user_handle}

        if full:
            data.update({   'id' : str(self.id),
                            'name' : self.name,
                            'email' : self.email,
                            'api_key' : self.api_key,
                            'rank' : self.rank,
                            'created' : self.created,
                            'active' : self.active})
        return data

    class Meta:
        db_table = 'User'
        indexes = [
            models.Index(fields=['email']),
            models.Index(fields=['api_key']),
        ]
        index_together = ("handle", "number")


class Engine(models.Model):
    name = models.CharField(max_length=16, unique=True)
    description = models.CharField(max_length=256)
    path = models.CharField(max_length=256)
    obj_name = models.CharField(max_length=32)

    developer = models.ForeignKey('User', on_delete=models.CASCADE)
    active = models.BooleanField(default=False)

    @property
    def rank(self):
        #   TODO: Complete
        #return len(self.applied)
        return 0

    def dump(self, full=False):
        data = {'name' : self.name,
                'description' : self.description,
                'rank' : self.rank,
                'developer' : self.developer.user_handle}

        if full:
            data.update({'path' : self.path})

        return data

    class Meta:
        db_table = 'Engine'
        indexes = [
            models.Index(fields=['name']),
        ]


#   TODO: Create scheme for tracking applied metadata for engines
#
#class AppliedEngine(models.Model):
#    engine_id = models.ForeignKey(Engine)
#    sample_id = models.ForeignKey(Sample)
#    user_id =   models.ForeignKey(User)
#    engine_metadata_id  = models.BigIntegerField();
#
#    class Meta:
#        db_table = 'AppliedEngine'
#        unique_together = ("sample_id", "user_id", "engine_metadata_id")

class AppliedMetadata(models.Model):
    metadata = models.ForeignKey('Metadata', on_delete = models.CASCADE)
    sample = models.ForeignKey('Sample', on_delete = models.CASCADE)
    user =   models.ForeignKey('User', on_delete = models.CASCADE)

    class Meta:
        db_table = 'AppliedMetadata'
        unique_together = ("metadata", "sample", "user")


class MetadataDetails(models.Model):
    name = models.CharField(max_length=256)
    prototype = models.CharField(max_length=256)
    comment = models.CharField(max_length=512)
    committed = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'MetadataDetails'


class Metadata(models.Model):
    id = models.BigAutoField(primary_key=True)

    user = models.ForeignKey('User', on_delete = models.CASCADE)
    details = models.ManyToManyField('MetadataDetails')

    @property
    def rank(self):
        if hasattr(self, 'id'):
            return AppliedMetadata.objects.filter(metadata=self.id).count()

        return 0

    def has_changed(self, name, prototype, comment):
        if not self.details.exists():
            return True

        latest = self.details.latest('committed')
        if ((latest.name != name)
            or (latest.prototype != prototype)
            or (latest.comment != comment)):
            return True

        return False

    def dump(self, full=False):
        data = {'creator' : self.user.user_handle}
        latest_details = self.details.latest('committed')
        data.update({
            'name' : latest_details.name,
            'prototype' : latest_details.prototype,
            'comment' : latest_details.comment,
            'rank' : self.rank
        })

        if full:
            #   Convert committed time back with:
            #   datetime.datetime.strptime(<dt>, '%Y-%m-%dT%H:%M:%S.%f')
            data['history'] = [{'name' : d.name,
                                'prototype' : d.prototype,
                                'comment' : d.comment,
                                'committed' : d.committed.isoformat()}
                                for d in self.details.order_by('committed')]

        return data

    class Meta:
        db_table = 'Metadata'
        indexes = [models.Index(fields=['user'])]


class FunctionApis(models.Model):
    api = models.CharField(max_length=128, unique=True)

    class Meta:
        db_table = 'FunctionApis'


class Function(models.Model):
    id = models.BigAutoField(primary_key=True)

    sha256 = models.CharField(max_length=64)
    opcodes = models.BinaryField()
    apis = models.ManyToManyField('FunctionApis')
    metadata = models.ManyToManyField('Metadata')
    architecture = models.CharField(max_length=64)

    def dump(self, full=False):
        data = {'opcodes' : self.opcodes,
                'architecture' : self.architecture,
                'sha256' : self.sha256}

        if full:
            data['apis'] = [x['api'] for x in self.apis.values('api')]
            data['id'] = self.id

        return data

    class Meta:
        db_table = 'Function'
        unique_together = ('sha256', 'architecture')


class Sample(models.Model):
    id = models.BigAutoField(primary_key=True)

    md5 = models.CharField(max_length=32)
    crc32 = models.BigIntegerField()
    sha1 = models.CharField(max_length=40, null=True, blank=True)
    sha256 = models.CharField(max_length=64, null=True, blank=True)
    seen_by = models.ManyToManyField('User')
    functions = models.ManyToManyField('Function')
    last_seen = models.DateTimeField(default=timezone.now, blank=True)

    class Meta:
        db_table = 'Sample'
        index_together = ['md5', 'crc32']
        unique_together = ('md5', 'crc32')

    def dump(self):
        return {'md5' : self.md5, 'crc32' : self.crc32,
                'seen_by' : [str(x.id) for x in self.seen_by.all()],
                'functions' : [str(x.id) for x in self.functions.all()],
                'sha1' : self.sha1,
                'sha256' : self.sha256}

server/www/views.py
#   Python Modules
import re

#   Django Modules
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.views.decorators.http import require_GET, require_POST, require_http_methods


#   FIRST Modules
from first_core.models import Function, User
from first_core.auth import Authentication, require_login, FIRSTAuthError

def handler404(request, exc):
    return render(request, 'www/404.html', None)


def index(request):
    data = {'title' : 'Home',
            'user_num' : User.objects.count(),
            'function_num' : Function.objects.count(),
            'register_html' : True,
            'login_html' : True,}
    return render(request, 'www/index.html', data)

@require_login
def profile(request):
    '''
    Should show the user's name, email, ranking and API key
    '''
    if 'info' not in request.session:
        return redirect(reverse('www:login'))

    info = request.session['info']
    user = Authentication.get_user_data(info['email'])

    if not user:
        return redirect(reverse('www:index'))

    count = Function.objects.filter(metadata__user=user).count()
    data = {'title' : 'Profile',
            'user' : user.dump(True),
            'metadata_count' : count}
    return render(request, 'www/profile.html', data)

def logout(request):
    request.session.flush()
    return HttpResponse('Logout')


@require_GET
def login(request, service=None):

    #   Check for errors
    #+++++++++++++++++++
    if request.GET.get('error'):
        return 'Access Denied'

    auth = Authentication(request)
    if auth.is_logged_in:
        return redirect('www:profile')

    if None == service:
        return redirect('www:index')

    request.session['redirect'] = 'www:profile'

    try:
        return auth.login_step_1(service, request.build_absolute_uri(reverse('www:oauth', kwargs={'service' : service})))

    except FIRSTAuthError as e:
        return HttpResponse(('Error: {}<br /><a href="/#login">Try logging '
                            'in again</a>').format(e))


@require_GET
def oauth(request, service):
    try:
        uri = 'www:profile'
        if 'redirect' in request.session:
            uri = request.session['redirect']
            del request.session['redirect']

        logging_in = uri == 'www:profile'
        if request.GET.get('code'):
            auth_code = request.GET['code']

            auth = Authentication(request)
            return auth.login_step_2(auth_code, reverse(uri), logging_in)

    except FIRSTAuthError as e:
        if 'registered' in str(e):
            return HttpResponse(('Error: {}<br /><a href="/">Register to use '
                                'FIRST</a>').format(e))

        return HttpResponse(('Error: {}<br /><a href="/">Try logging in '
                            'again</a>').format(e))

    except RuntimeError as e:
        return redirect('www:profile')

    return redirect('www:index')

@require_GET
def logout(request):
    request.session.flush()
    return redirect('www:index')

@require_http_methods(['POST', 'GET'])
def register(request):
    '''
    Required: handle
    Get name and email from sign in service
    '''

    #   Check for errors
    #+++++++++++++++++++
    if 'error' in request.GET:
        return HttpResponse('Access Denied')

    auth = Authentication(request)
    if request.method == 'POST':
        if not request.POST.get('service') or not request.POST.get('handle'):
            return redirect('www:index', _anchor='registration')

        #   TODO: Input Validation
        request.session['redirect'] = 'www:register'
        if not re.match('^[A-Za-z_\d]+$', request.POST.get('handle')):
            return HttpResponse('Invalid handle')

        request.session['handle'] = request.POST.get('handle')
        service = request.POST.get('service')

        try:
            return auth.login_step_1(service, reverse('www:oauth', kwargs={'service' : service}))

        except FIRSTAuthError as e:
            return HttpResponse(('Error: {}<br /><a href="/#login">Try logging '
                                'in again</a>').format(e))

        return HttpResponse('No post data provided')


    if request.method == 'GET':
        if auth.is_logged_in:
            if ('info' not in request.session or 'email' not in request.session['info']):
                raise FIRSTAuthError('Email not set')

            user = Authentication.get_user_data(request.session['info']['email'])
            if not user:
                if 'handle' in request.session:
                    user = auth.register_user()
                    if not user:
                        return HttpResponse('Error creating user')

                return redirect(reverse('www:profile'))

            return HttpResponse('User already exists')

        return HttpResponse('Not logged in')

server/www/templates/www/index.html
{% extends 'www/base_site.html' %}
{% load static %}

{% block content %}
            <section id="home">
                <div class="rev_slider_wrapper">
                    <div class="rev_slider" id="slider5" data-version="5.0">
                        <ul style="background-color: #45738c;">

                            <li data-transition="scaleleftfromright"
                                data-easein="default"
                                data-easeout="default"
                                data-slotamount="4"
                                data-masterspeed="600"
                                data-delay="8000"
                                data-title="FIRST"
                            >
                                <!-- MAIN IMAGE -->
                                <img src="{% static 'www/img/logo.png' %}"
                                     alt=""
                                     data-bgrepeat="no-repeat"
                                     data-bgparallax="7"
                                     class="rev-slidebg"
                                >

                                <!-- LAYER NR. 1 -->
                                <div class="tp-caption hero-text giant_nocaps rs-parallaxlevel-7"
                                     data-x="center"
                                     data-y="center"
                                     data-transform_idle="o:1;s:1000;"
                                     data-transform_in="y:-50px;opacity:0;s:1500;e:Power3.easeOut;"
                                     data-transform_out="opacity:0;sX:0;sY:0;s:2000;e:Power3.easeInOut;"
                                     data-start="1000">
                                    <!--FIRST-->
                                    <img src="{% static 'www/img/first_logo.png' %}"/>
                                </div>

                                <!-- LAYER NR. 2 -->
                                <div class="tp-caption rs-parallaxlevel-7"
                                     data-x="center"
                                     data-y="center"
                                     data-voffset="143"
                                     data-hoffset="0"
                                     style="z-index: 13; max-width: auto; max-height: auto; white-space: nowrap; padding-top: 15px;">
                                    <div id="main_content" align="center">
                                        <a href='#' class='btn btn-lg btn-transparent' data-toggle="modal"
                                           data-target="#modalRegistration">Register</a>
                                        <a href='https://github.com/vrtadmin/FIRST' target="_blank"
                                           class='btn btn-lg btn-color'>Download</a>
                                    </div>
                                </div>


                            </li>

                        </ul>

                        <div class="local-scroll-no-offset">
                            <a href="#about" class="scroll-down">
                                <i class="fa fa-angle-down"></i>
                            </a>
                        </div>

                    </div>
                </div>
            </section>

            <section class="section-wrap intro" id="about">
                <div class="container-fluid">
                    <div class="row">

                        <div class="text-center">
                            <div class="wow slideInDown" data-wow-duration="1.2s"
                                 data-wow-delay="0s">
                                <h2 class="intro-heading heading-frame">
                                    Welcome to First
                                </h2>
                            </div>
                            <div class="container">
                                <div class="row mt-minus-30">

                                    <div class="col-sm-6 wow slideInLeft" align="left" data-wow-duration="1.2s"
                                         data-wow-delay="0s">
                                        <div class="about-description mt-30">
                                            <h4>About Us</h4>
                                            <p class="mb-60">
                                                The Function Identification and Recover Signature Tool (FIRST) developed by
                                                Talos, is an IDA Pro
                                                plugin that
                                                allows reverse engineers to more quickly complete static analysis. It makes
                                                finding similar
                                                functions faster and easier by removing the need to synchronize function
                                                metadata. 
                                            </p>
                                            <p>
                                                FIRST’s extensible framework allows users to submit function metadata to a
                                                repository and
                                                search the repository for function metadata similar to the function
                                            </p>
                                        </div>
                                    </div> <!-- end col -->

                                    <div class="col-sm-6 wow slideInRight" align="left" data-wow-duration="1.2s"
                                         data-wow-delay="0s">
                                        <div id="skills" class="skills-progress">
                                            <h4>Goals</h4>
                                            <p>
                                                Users can contribute function metadata and search for function metadata
                                                similar to the function(s) being analyzed in IDA. FIRST’s framework allows
                                                developers to create new ways to derive similarities between functions.
                                            </p>
                                            <ul style="list-style: circle; padding-left: 25px;">
                                                <li>
                                                    Save function metadata (name, prototype, and comment)

                                                </li>
                                                <li>
                                                    Provide way to find similar functions
                                                </li>
                                                <li>
                                                    Allow users to apply function metadata in IDA Pro
                                                </li>
                                                <li>
                                                    Reduce reverse engineering time
                                                </li>
                                            </ul>
                                        </div>
                                    </div> <!-- end col -->

                                </div>
                            </div>
                            <div class="wow slideInUp" data-wow-duration="1.2s"
                                 data-wow-delay="0s">
                                <img src="{% static 'www/img/intro_logo.png' %}" alt=""/>
                            </div>
                        </div>

                    </div>
                </div>
            </section> <!-- end intro -->

            <section class="result-boxes">
                <div class="container-fluid">
                    <div class="row">

                        <div class="col-lg-6 col-md-12 nopadding wow slideInLeft" data-wow-duration="1.2s"
                             data-wow-delay="0s">
                            <div class="statistic result-box result-box-second">
                                <div class="result-wrap clearfix">
                                    <i class="icon icon-User"></i>
                                    <span class="timer" data-from="0" data-to="{{ user_num | default:'0' }}"></span>
                                    <span class="counter-text">Users</span>
                                </div>
                            </div>
                        </div> <!-- end second result box -->

                        <div class="col-lg-6 col-md-12 nopadding wow slideInRight" data-wow-duration="1.2s"
                             data-wow-delay="0s">
                            <div class="statistic result-box result-box-third">
                                <div class="result-wrap clearfix">
                                    <i class="icon icon-Settings"></i>
                                    <span class="timer" data-from="0" data-to="{{ function_num | default:'0' }}"></span>
                                    <span class="counter-text">Functions</span>
                                </div>
                            </div>
                        </div> <!-- end third result box -->

                    </div>
                </div>
            </section> <!-- end results-->
{% endblock %}

server/www/templates/www/profile.html
{% extends 'www/base_site.html' %}

{% block nav_block %}
<ul class="nav navbar-nav local-scroll-no-offset text-center">

    <li class="active">
        <a href="{% url 'www:index' %}">Home</a>
    </li>
    <li>
        <a href="#profile">Profile</a>
    </li>
    <li>
        <a href="#requirement">Requirements &amp; Installation</a>
    </li>
    <li>
        <a href="#submit_engine">Submit Engine</a>
    </li>
    <li>
        <a target="_blank" href="https://github.com/vrtadmin/FIRST/releases">Download</a>
    </li>
    <li>
        <a href="{% url 'www:logout' %}">Logout</a>
    </li>


</ul>
{% endblock %}
{% block content %}
    <section class="section-wrap intro" id="profile">
      <div class="container-fluid">
        <div class="row">
          <div class="text-center">
            <div class="wow slideInDown" data-wow-duration="1.2s"
                 data-wow-delay="0s">
              <h2 class="intro-heading heading-frame">

                Welcome <span style="color:#F29614">{{ user.name }}</span>

              </h2>
            </div>
          </div>
        </div>
      </div>
    </section> <!-- end intro -->

    <section class="result-boxes profile_container">
      <div class="container-fluid">
        <div class="row">

          <div class="col-lg-6 col-md-12 nopadding wow slideInDown" data-wow-duration="1.2s"
               data-wow-delay="0s">
            <div class="statistic result-box result-box-second">
              <div class="result-wrap clearfix">
                <i class="icon icon-Key"></i>
                <h4>
                  {{ user.api_key }}
                </h4>
                <span class="counter-text">API Key</span>
              </div>
            </div>
          </div> <!-- end second result box -->

          <div class="col-lg-6 col-md-12 nopadding wow slideInRight" data-wow-duration="1.2s"
               data-wow-delay="0s">
            <div class="statistic result-box result-box-third">
              <div class="result-wrap clearfix">
                <i class="icon icon-Wrench"></i>
                <h4>
                  {{ user.handle }}
                </h4>
                <span class="counter-text">Handle</span>
              </div>
            </div>
          </div> <!-- end third result box -->

          <div class="col-lg-6 col-md-12 nopadding wow slideInLeft" data-wow-duration="1.2s"
               data-wow-delay="0s">
            <div class="statistic result-box result-box-third">
              <div class="result-wrap clearfix">
                <i class="icon icon-Star"></i>
                <h4>
                  {{ user.rank }}
                </h4>
                <span class="counter-text">Karma LVL</span>
              </div>
            </div>
          </div> <!-- end second result box -->

          <div class="col-lg-6 col-md-12 nopadding wow slideInUp" data-wow-duration="1.2s"
               data-wow-delay="0s">
            <div class="statistic result-box result-box-second">
              <div class="result-wrap clearfix">
                <i class="icon icon-Tag"></i>
                <h4>
                  {{ metadata_count | default:'0' }}
                </h4>
                <span class="counter-text">MetaData</span>
              </div>
            </div>
          </div> <!-- end third result box -->

        </div>
      </div>
    </section> <!-- end results-->
{% endblock %}